# Site settings
title: Dr SangJoon Kwak blog
email: 
description: "For Sustainable Healthcare System"
baseurl: ""
url: "http://drsangjoonkwak.github.io"
twitter_username: drsangjoonkwak
github_username:  drsangjoonkwak

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
